# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: middleman-tako 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "middleman-tako"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dunya Kirkali"]
  s.date = "2014-01-18"
  s.description = "Tako's middleman template: Slim, Redcarpet, html5, ..."
  s.email = "dunyakirkali@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "features/cli_init.feature",
    "features/support/env.rb",
    "lib/middleman-tako.rb",
    "lib/middleman-tako/template.rb",
    "lib/middleman-tako/template/shared/Gemfile.tt",
    "lib/middleman-tako/template/shared/config.tt",
    "lib/middleman-tako/template/source/index.slim",
    "lib/middleman-tako/template/source/layouts/application.slim",
    "lib/middleman_extebsion.rb",
    "middleman-tako.gemspec",
    "test/helper.rb",
    "test/test_middleman-tako.rb"
  ]
  s.homepage = "http://github.com/dunyakirkali/middleman-tako"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Tako's middleman template"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<middleman>, ["~> 3.2"])
      s.add_runtime_dependency(%q<slim>, ["~> 2.0"])
      s.add_runtime_dependency(%q<redcarpet>, ["~> 3.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, "~> 6.3")
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<aruba>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<middleman>, ["~> 3.2"])
      s.add_dependency(%q<slim>, ["~> 2.0"])
      s.add_dependency(%q<redcarpet>, ["~> 3.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, "~> 6.3")
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<aruba>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<middleman>, ["~> 3.2"])
    s.add_dependency(%q<slim>, ["~> 2.0"])
    s.add_dependency(%q<redcarpet>, ["~> 3.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, "~> 6.3")
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<aruba>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

